### ISSUE TITLE
Update  and examples on documentation on Card

### ISSUE THREAD

**Issue by alinaradu** [NGRP/node-red-contrib-viseo#110]
The Card documentation is partially inaccurate.
Here are a few remarks:

Types:

1. Text - typo

2. Image 
-- url: test for https
-- provide example for server path
3. Card
- Text - non documented - give example with mustache and say the root of the provided expression is always msg:
{payload[0].SKU} = msg.payload[0].SKU

- Replace Subtitle with Subtext - mustache example. Root is always msg.
- Replace Attachement with Image
- Shared card - break line

4. Buttons properties:
Show image - break lines. Example of URL 
Post-back - PB/IMB ?
Dynamic buttons :
- add how to "delete" the buttons - not clear enough.
Card - include an image 
Carousel - include an image

**Comment by Klervix** [comment]
**Hello** @alinaradu,
Feel free to make a pull request to update the documentation :)
