### ISSUE TITLE
Loop node

### ISSUE THREAD

**Issue by TothiViseo** [NGRP/node-red-contrib-viseo#35]
Create a node that performs a sequential loop over an array.

use cases : 
- A list a messages that can be sent one at a time (and respect the delay time)
- The display of a carousel of cards

**Comment by Klervix** [comment]
New loops management node available [here](https://github.com/NGRP/node-red-contrib-viseo/tree/master/node-red-contrib-loops).

**Comment by Klervix** [comment]
New loops management node available [here](https://github.com/NGRP/node-red-contrib-viseo/tree/master/node-red-contrib-loops).
