### ISSUE TITLE
No instructions on how to get going

### ISSUE THREAD

**Issue by TotallyInformation** [NGRP/node-red-contrib-viseo#59]
OK, so you have some instructions for installation. But what then? Nothing?

**Comment by JpEncausse** [comment]
All the documentation is in the wiki:
https://github.com/NGRP/node-red-contrib-viseo/wiki/Getting-started#user-content-installation

It will be improved (for windows) later

**Comment by TotallyInformation** [comment]
Thanks, I've followed all that and - as per my other issue - even got it working on Windows. However, there are no instructions on how to set up a bot using your framework.

**Comment by JpEncausse** [comment]
In a nutshell, you put a botbuilder server then you pipe messages.

Documentation for bots is in botbuilder folder:
https://github.com/NGRP/node-red-contrib-viseo/tree/master/node-red-contrib-botbuilder

It will be updated, cleaned and moved later

**Comment by samuelguesnier** [comment]
Yes it would be great if we had a tutorial ! ;)
For example how to handle facebook payload ( to say hi {name})

**Comment by JpEncausse** [comment]
Hi,
Did you follow the documentation of My First Bot ? 
https://github.com/NGRP/node-red-contrib-viseo/wiki/My-first-bot

- Create a Bot in BotFramework (juste follow Microsoft instruction)
- Add channel to Messenger (also explain by Microsoft)
- Use the BotBuilder node with the BotFramework's credential
- Add a Message node
- Give it a try

To add the {name} you'll have to add the Profile node

**Comment by samuelguesnier** [comment]
Hey ! 
Yes the bot is working but but I maybe need to try things more to fully understand
