### ISSUE TITLE
Bug - can't find handleData / phantomjs

### ISSUE THREAD

**Issue by paxinos** [NGRP/node-red-contrib-viseo#60]
Greetings, 

I've installed node-red-contrib-phantomjs and am having problems with the demo flow...   seems handleData can not be found...

22 Sep 17:36:52 - [info] stderr:Console: ReferenceError: Can't find variable: handleData (from line # in "")

The resulting PNG is the right size, but it is black.   Accessing /chart renders a chart.

One thing I do plan on changing is supporting URL to be passed in a msg...

**Comment by JpEncausse** [comment]
Hum,
- We use this module in a production bot but I didn't test it since a few month
- I know that PhantomJS has issues with Fonts and Graphics on linux (there is requirement)
- In the roadmap we also should replace PhantomJS by Chromeless (a new Webkit in Node)

**Comment by paxinos** [comment]
any suggestions on what I can look for regarding the missing 'handleData' ?   I don't see it referenced in any of the files.

Thanks.

**Comment by JpEncausse** [comment]
It seems to work for me with the demo flow

The `handleData()` is defined in the `D3 Bar Chart` node it is called from `phantomjs-script-snapshot.js` but is not required.
