### ISSUE TITLE
prod command not found

### ISSUE THREAD

**Issue by samuelguesnier** [NGRP/node-red-contrib-viseo#62]
Hello ! 
When I try to run the template, I get this error "prod: command not found"
Have you a solution ?
Thank you for your help :)

**Comment by JpEncausse** [comment]
Hi,

Which template ?
- the template with windows release (with SARAH nodes)
- or the viseo-bot-template

**Comment by samuelguesnier** [comment]
It is the viseo-bot template

**Comment by samuelguesnier** [comment]
I tried on my friend's PC,  his PC is on Linux Mint  and the same probleme happens. So, I think i'm doing something wrong.
What I do is : 
- I go on my bot folder and I type this : bash ../framework/start.sh [ -p port ] [ --url http://url ] --env [ dev|prod ] [ --credential-secret salut] bot

**Comment by JpEncausse** [comment]
I update the documentation you should type something more like this:

`../bot-framework/start.sh -p 1880 --env dev --credential-secret yout-secret MyFirstBot`

**Comment by samuelguesnier** [comment]
Thank you very much for your help. It is working :+1:
