### ISSUE TITLE
error neDB "No such file or directory"

### ISSUE THREAD

**Issue by samuelguesnier** [NGRP/node-red-contrib-viseo#66]
Hey :) 

I get this bug and I do not know why because I have no database channel

https://image.noelshack.com/fichiers/2017/42/3/1508349401-capture-du-2017-10-18-19-56-28.png
I tried to create the file but it still printing this message

`/home/ubuntu/[bot]/bot/data/database.db - Error: ENOENT: no such file or directory, rename '/home/ubuntu/[bot]/bot/data/database.db~' -> '/home/ubuntu/[bot]/bot/data/database.db'`
Have you an idea why ?
Thank you

**Comment by samuelguesnier** [comment]
Fixed ! I just created a new bot and  the bug was gone. :+1:

**Comment by JpEncausse** [comment]
Sometimes NeDB has hard time loading files. I have this error on windows when DropBox try to sync the file while loading.

We design a database node that can work with neDB but Aldo MongoDB or CosmoDB you can give it a try in production

**Comment by samuelguesnier** [comment]
Thank you JP, I'll try
