### ISSUE TITLE
[Question] How Configure ms-luis-config node

### ISSUE THREAD

**Issue by holl59** [NGRP/node-red-contrib-viseo#75]
Hi,

After publish my app with a good azure key, i configurated the node with : 
  - host : the full url starting with https://westus.api.cognitive.microsoft.com...
  - appID : the appID in [setting]
  - subKey : one of the key string

After test, i have the error message : [ms-luis:Luis] StatusCodeError: 400 - "An item with the same key has already been added."

Can you explain, how have a good configuration ?

Thanks
Regards

**Comment by TothiViseo** [comment]
Hello,

The problem might lie with the host parameter if you gave the whole url.
Could you try putting in https://westus.api.cognitive.microsoft.com ?

The node actually builds the complete url from the app Id and the key, so if you put the whole url as host you might be giving twice the same piece of information.

Thank you
Best Regards

**Comment by holl59** [comment]
Great, it's OK :)
