### ISSUE TITLE
node-red-contrib-viseo-dialogflow Question

### ISSUE THREAD

**Issue by Paul-Reed** [NGRP/node-red-contrib-viseo#76]
Are there any guides or notes how to use this node please.
Is it used by adding a http input (GET) node & a http response node, and adding the url to dialogflow fullfillment (webhook)?

**Comment by Klervix** [comment]
Hi, 
You can try this node using a simple "inject" node with a string (ex: "hello").
Put your client key in the 'tokens' field of the node.
The node sends a request and returns the response in the msg.payload field.
