### ISSUE TITLE
node-red-contrib-viseo-dialogflow - Errors on deployment

### ISSUE THREAD

**Issue by Paul-Reed** [NGRP/node-red-contrib-viseo#77]
Just added the dialogflow via NR's palette manager, but despite adding the required entries for the api v2, whenever I try and deploy, NR stops with the following error;
```
23 Dec 19:39:01 - [info] Waiting for missing types to be registered:
23 Dec 19:39:01 - [info]  - dialogflow
```
I've tried fresh installations twice now, and got same result.
0.17.5: Maintenance Release running on Raspian Stretch

**Comment by yellowiscool** [comment]
I have the same issue. The node disappeared from the input nodes panel as well.

**Comment by Klervix** [comment]
Hi!
Do you still have this problem? Did you try to update the node (npm update)?

**Comment by Paul-Reed** [comment]
The issue was posted 3 months ago, and as I got no response I deleted the node as chose a different solution.
