### ISSUE TITLE
node-red-contrib-google-spreadsheet not fetching new data

### ISSUE THREAD

**Issue by schieska** [NGRP/node-red-contrib-viseo#83]
I am only getting changed data on restart of node-red server.

**Comment by Klervix** [comment]
Hi!
I'm so sorry about that, I totally forgot to tell something about that point in documentation.
To avoid multiple calls to Spreadsheet, the node uses a field (default: global._sheet) to stock data. It's the "Save" parameter of the node. So the node will request Sheets API only if this field is empty.

Two solutions:
- If you want to call the Sheets API every time, please insert a "change" node to delete the global._sheet field BEFORE using the Spreadsheet node ;
- Or just add an "inject" node somewhere in your flow to delete the global._sheet field only when you've done some changes in your Spreadhsheet.

Thanks for asking and tell me if I'm not clear :)
