### ISSUE TITLE
FR: jimp - add more functions (resize, rotate, etc)

### ISSUE THREAD

**Issue by M0ebiu5** [NGRP/node-red-contrib-viseo#86]
Currently the "jimp node" only supports cropping, but the jimp library offers more image manipulation function. 

Because of the name, it would be nice, if the node would support at least the most used jimp functions. Otherwise it should be renamed to "node-red-contrib-jimp-crop", cause the current naming implies that it's a wrapper to the whole jimp library.

**Comment by JpEncausse** [comment]
For now it only support croping and will evolve later that's why it is called node-red-....-jimp.
It is called node-red-contrib-viseo-jimp in NPM and not node-red-contrib-jimp because this node is part of a larger library
