### ISSUE TITLE
pasword SARAH V5

### ISSUE THREAD

**Issue by cowbra** [NGRP/node-red-contrib-viseo#89]
hello,
I have installed sarah V5 on vm machine, all works, but when i go on the web page of sarah,
I need a password an an username. What are they ?
thank you

**Comment by arimk** [comment]
Hi,
As the docs explains it, you are supposed to set it up. Default one is demo / loremipsum if I am no mistaken.
https://github.com/NGRP/node-red-contrib-viseo/wiki/Getting-started#configure-the-viseo-bot-maker

**Comment by Klervix** [comment]
I close this issue, but feel free to reopen it if it does not work.
