### ISSUE TITLE
node-red-contrib-viseo-google-spreadsheet:  Set data

### ISSUE THREAD

**Issue by cbsantos** [NGRP/node-red-contrib-viseo#91]
Hello, 

I am using the node-red-contrib-viseo-google-spreadsheet to write. 
The google sheet accept the registry of an array but, each letter in a string is recorded in one different cell in the sheet. What I am missing? 

cheers

**Comment by Klervix** [comment]
Hi cbsantos!
Maybe you are trying to put data from an array, like : ["Red", "Blue", "Pink", "Yellow"].
But one array is for the lines, one for the columns. Try with : [["Red", "Blue", "Pink", "Yellow"]], or [["Red"], ["Blue"], ["Pink"], ["Yellow"]]. Is it better?

**Comment by cbsantos** [comment]
Hi Klervix!

Thank you very much!
It is working now. 
Sorry for this silly question. 

Cheers, 

Cesar
