### ISSUE TITLE
Sample application in node-red-contrib-viseo-ms-graph broken. 

### ISSUE THREAD

**Issue by broo0ose** [NGRP/node-red-contrib-viseo#94]
Hi,

I'm looking at **node-red-contrib-viseo-ms-graph**, trying to understand it. 
I downloaded the sample application mentioned in the documentation at https://flows.nodered.org/node/node-red-contrib-viseo-ms-graph. 

But the node names do not match the names in the library. 
In the sample there is a node type **ms-graph-oauth** but this seems to be called **ms-graph** in the current version. 

Also I can't find where **send-card** comes from and **nedb** is a dependency which is not mentioned but easily fixed.

Edit: OK send-card is from node-red-contrib-viseo-bot-message. Also when installing the nodes there's a node.js dependency of **request** and **request-promise**. 

thanks for reading

**Comment by Klervix** [comment]
Hi,

Sorry, the doc was a bit old and we forgot to delete it... 
I just push the 0.2.6 version on Github.
